// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Repositories.Sql;

#nullable disable

namespace Portfolio.Repositories.Sql.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260727112749_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Repositories.Sql.CopyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Lang")
                        .IsUnique();

                    b.ToTable("CopyEntry", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.CoverPresetRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bottom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Top")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CoverPreset", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.DemoRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("Demo", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.FactRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("Fact", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.GameRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.HeroRoleRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Lang", "Order");

                    b.ToTable("HeroRole", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.RepoRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Updated")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("Repo", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.SiteMetaRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Github")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GithubUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Play")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("SiteMeta", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.TechRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("Tech", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.TerminalLogRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("TerminalLog", (string)null);
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.DemoRow", b =>
                {
                    b.OwnsOne("Portfolio.Entities.Content.Localized", "Desc", b1 =>
                        {
                            b1.Property<int>("DemoRowId")
                                .HasColumnType("int");

                            b1.Property<string>("En")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescEn");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescRu");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescTr");

                            b1.HasKey("DemoRowId");

                            b1.ToTable("Demo");

                            b1.WithOwner()
                                .HasForeignKey("DemoRowId");
                        });

                    b.Navigation("Desc")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.FactRow", b =>
                {
                    b.OwnsOne("Portfolio.Entities.Content.Localized", "Label", b1 =>
                        {
                            b1.Property<int>("FactRowId")
                                .HasColumnType("int");

                            b1.Property<string>("En")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasDefaultValue("")
                                .HasColumnName("LabelEn");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasDefaultValue("")
                                .HasColumnName("LabelRu");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasDefaultValue("")
                                .HasColumnName("LabelTr");

                            b1.HasKey("FactRowId");

                            b1.ToTable("Fact");

                            b1.WithOwner()
                                .HasForeignKey("FactRowId");
                        });

                    b.Navigation("Label")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.GameRow", b =>
                {
                    b.OwnsOne("Portfolio.Entities.Content.Localized", "Desc", b1 =>
                        {
                            b1.Property<int>("GameRowId")
                                .HasColumnType("int");

                            b1.Property<string>("En")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescEn");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescRu");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescTr");

                            b1.HasKey("GameRowId");

                            b1.ToTable("Game");

                            b1.WithOwner()
                                .HasForeignKey("GameRowId");
                        });

                    b.Navigation("Desc")
                        .IsRequired();
                });

            modelBuilder.Entity("Portfolio.Repositories.Sql.RepoRow", b =>
                {
                    b.OwnsOne("Portfolio.Entities.Content.Localized", "Desc", b1 =>
                        {
                            b1.Property<int>("RepoRowId")
                                .HasColumnType("int");

                            b1.Property<string>("En")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescEn");

                            b1.Property<string>("Ru")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescRu");

                            b1.Property<string>("Tr")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasDefaultValue("")
                                .HasColumnName("DescTr");

                            b1.HasKey("RepoRowId");

                            b1.ToTable("Repo");

                            b1.WithOwner()
                                .HasForeignKey("RepoRowId");
                        });

                    b.Navigation("Desc")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
